name:  Hello Workflow

on:  
  workflow_dispatch:
  push:

jobs:
  echo-hello:
    runs-on:  ubuntu-latest
    steps:
      - name:  Say hello
        run: echo "Hello, world!"
      - name:  Multi-line bash
        run:  | 
          echo  "I am"
          echo  "a multi-line"
          echo  "script."

  echo-goodbye:
      runs-on:  ubuntu-slim
      steps:
         - name:  Say Goodbye
           run:  echo "Goodbye! ......"
