name:  Hello Workflow

on:  
  workflow_dispatch:
  push:

jobs:
  echo-hello:
    runs-on:  ubuntu-latest
    if: github.event_name == 'push' 
    steps:
      - name:  Say hello
        run: echo "Hello, world!"
      - name:  Multi-line bash
        run:  | 
          echo  "I am"
          echo  "a multi-line"
          echo  "script."

  echo-goodbye:
      runs-on:  ubuntu-slim
      steps:
         - name:  Say Goodbye
           run:  echo "Goodbye! ......"
         - name: Event name
           run: |
             echo "Event name: ${{ github.event_name }}"

  ubuntu-echo:
    needs:  echo-goodbye
    runs-on:  ubuntu-latest
    steps:
      - name:  Show OS
        run:  | 
          echo  "The job is running on an Ubuntu runner."
          echo  "Runner OS: $RUNNER_OS"
          
  windows-echo:
      needs:  ubuntu-echo
      runs-on:  windows-latest
      steps:
        - name:  Show OS
          shell: bash
          run:  | 
            echo  "The job is running on an Windows runner."
            echo  "Runner OS: $RUNNER_OS"



